name: Deploy docs

on:
  push:
    branches:
      - "main"
    paths:
      - "docs/**"
      - "*.lua"
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Build
    uses: ./.github/workflows/buildDocs.yml

  deploy:
    needs: build
    if: github.event_name != 'pull_request' && github.ref == 'refs/heads/main'

    permissions:
      pages: write
      id-token: write

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to pages
        uses: actions/deploy-pages@v5
